# Generated by Django 4.2.11 on 2024-05-06 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0003_alter_wiki_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wiki',
            name='text',
            field=models.TextField(verbose_name='Описаниe'),
        ),
    ]
