# Generated by Django 4.2.11 on 2024-05-14 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0004_alter_wiki_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_likes', to=settings.AUTH_USER_MODEL, verbose_name='Поставил лайк')),
                ('wiki_like', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wiki_likes', to='wiki.wiki', verbose_name='Лайкнутая статья')),
            ],
        ),
    ]
