# Generated by Django 4.2.11 on 2024-05-14 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0005_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dislike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_diser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_dislikes', to=settings.AUTH_USER_MODEL, verbose_name='Поставил лайк')),
                ('wiki_dislike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wiki_dislikes', to='wiki.wiki', verbose_name='Лайкнутая статья')),
            ],
        ),
    ]
