# Generated by Django 4.2.11 on 2024-05-14 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0006_dislike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dislike',
            name='user_diser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_dislikes', to=settings.AUTH_USER_MODEL, verbose_name='Поставил дислайк'),
        ),
        migrations.AlterField(
            model_name='dislike',
            name='wiki_dislike',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wiki_dislikes', to='wiki.wiki', verbose_name='Дислайкнутая статья'),
        ),
    ]
