# Generated by Django 4.2.11 on 2024-06-08 08:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0007_alter_dislike_user_diser_alter_dislike_wiki_dislike'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_prof', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('like_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_likes', to=settings.AUTH_USER_MODEL, verbose_name='Поставили лайк')),
            ],
        ),
        migrations.CreateModel(
            name='PortalFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_image', models.ImageField(upload_to='portal', verbose_name='Фото пользователя')),
                ('author_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор фото')),
            ],
        ),
        migrations.CreateModel(
            name='PortalDislake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_to_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_to_prof', to=settings.AUTH_USER_MODEL, verbose_name='Автор фото')),
                ('dislake_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dislake_images', to=settings.AUTH_USER_MODEL, verbose_name='Дислайков под фото')),
            ],
        ),
    ]
