# Generated by Django 4.2.11 on 2024-06-08 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0008_portallike_portalfoto_portaldislake'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portaldislake',
            name='dislake_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dislake_images', to='wiki.portalfoto', verbose_name='Дислайков под фото'),
        ),
        migrations.AlterField(
            model_name='portallike',
            name='like_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_likes', to='wiki.portalfoto', verbose_name='Поставили лайк'),
        ),
    ]
